# Author: Ali Gunes
# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'AboutUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AboutWindow(object):
    def setupUi(self, AboutWindow):
        AboutWindow.setObjectName("AboutWindow")
        AboutWindow.resize(420, 468)
        AboutWindow.setMaximumSize(QtCore.QSize(420, 468))

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/icons/university.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AboutWindow.setWindowIcon(icon)

        self.centralwidget = QtWidgets.QWidget(AboutWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")

        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")

        self.logoLabel = QtWidgets.QLabel(self.centralwidget)
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap("resources/img/esoguLogo.png"))
        self.logoLabel.setScaledContents(True)
        self.logoLabel.setObjectName("logoLabel")

        self.verticalLayout.addWidget(self.logoLabel)

        self.aboutLabel = QtWidgets.QLabel(self.centralwidget)
        self.aboutLabel.setWordWrap(True)
        self.aboutLabel.setObjectName("aboutLabel")

        self.verticalLayout.addWidget(self.aboutLabel)

        self.close_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.close_pushButton.setObjectName("close_pushButton")

        self.verticalLayout.addWidget(self.close_pushButton)

        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        AboutWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AboutWindow)
        self.close_pushButton.clicked.connect(AboutWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AboutWindow)

    def retranslateUi(self, AboutWindow):
        _translate = QtCore.QCoreApplication.translate
        AboutWindow.setWindowTitle(_translate("AboutWindow", "About"))
        self.aboutLabel.setText(_translate("AboutWindow", "This software was written by Ali Güneş for the Object-Oriented Programming II course, which was lectured by Asst. Prof. Dr. Burak Kaleci."))
        self.close_pushButton.setText(_translate("AboutWindow", "Close"))
