# Author: Ali Gunes
# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'LoadingUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QMovie
from PyQt5.QtCore import Qt

class Ui_LoadingWindow(object):
    def setupUi(self, LoadingWindow):
        LoadingWindow.setObjectName("LoadingWindow")
        LoadingWindow.setFixedSize(240, 120)
        LoadingWindow.setWindowFlags(Qt.WindowStaysOnTopHint | Qt.FramelessWindowHint)

        font = QtGui.QFont()
        font.setPointSize(10)
        LoadingWindow.setFont(font)

        self.centralwidget = QtWidgets.QWidget(LoadingWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

        self.loadingAnimation_label = QtWidgets.QLabel(self.centralwidget)
        self.loadingAnimation_label.setAlignment(QtCore.Qt.AlignCenter)
        self.loadingAnimation_label.setObjectName("loadingAnimation_label")
        self.verticalLayout.addWidget(self.loadingAnimation_label)

        self.loadingAnimation = QMovie("resources/img/loading.gif")
        self.loadingAnimation_label.setMovie(self.loadingAnimation)
        self.loadingAnimation.start()

        self.processing_label = QtWidgets.QLabel(self.centralwidget)
        self.processing_label.setAlignment(QtCore.Qt.AlignCenter)
        self.processing_label.setObjectName("processing_label")
        self.verticalLayout.addWidget(self.processing_label)

        LoadingWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoadingWindow)
        QtCore.QMetaObject.connectSlotsByName(LoadingWindow)

    def retranslateUi(self, LoadingWindow):
        _translate = QtCore.QCoreApplication.translate
        LoadingWindow.setWindowTitle(_translate("LoadingWindow", "LoadingWindow"))
        self.processing_label.setText(_translate("LoadingWindow", "Processing..."))



if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    LoadingWindow = QtWidgets.QMainWindow()
    ui = Ui_LoadingWindow()
    ui.setupUi(LoadingWindow)
    LoadingWindow.show()
    sys.exit(app.exec_())
